export enum USER_REGISTRATION {
  USERNAME_MIN_LENGTH = 6,
  USERNAME_MAX_LENGTH = 30,

  FISTNAME_MIN_LENGTH = 1,
  FISTNAME_MAX_LENGTH = 50,

  LASTNAME_MIN_LENGTH = 2,

  PASSWORD_MIN_LENGTH = 6,
  PASSWORD_MAX_LENGTH = 20,
}
