apiVersion: apps/v1
kind: Deployment
metadata:
  name: DEPLOYMENT_NAME
  namespace: NAMESPACE
  labels:
    app: PROJECT
spec:
  selector:
    matchLabels:
      project: PROJECT
  template:
    metadata:
      namespace: NAMESPACE
      labels:
        project: PROJECT
    spec:
      containers:
         - name: PROJECT
           image: REGISTRY_HOSTNAME/PROJECT:TAG_VERSION
           ports:
             - containerPort: PORT_CONTAINER

           env:
             - name: PG_PASSWORD
               valueFrom:
                 secretKeyRef:
                   name: back-incta-read-production-config-secret
                   key: PG_PASSWORD
             - name: PG_PORT
               valueFrom:
                 secretKeyRef:
                   name: back-incta-read-production-config-secret
                   key: PG_PORT
             - name: PG_HOST
               valueFrom:
                 secretKeyRef:
                   name: back-incta-read-production-config-secret
                   key: PG_HOST
             - name: PG_DATABASE
               valueFrom:
                 secretKeyRef:
                   name: back-incta-read-production-config-secret
                   key: PG_DATABASE
             - name: MODE
               valueFrom:
                 secretKeyRef:
                   name: back-incta-read-production-config-secret
                   key: MODE
             - name: PG_USER
               valueFrom:
                 secretKeyRef:
                   name: back-incta-read-production-config-secret
                   key: PG_USER
