apiVersion: apps/v1
kind: Deployment
metadata:
  name: DEPLOYMENT_NAME
  namespace: NAMESPACE
  labels:
    app: PROJECT
spec:
  selector:
    matchLabels:
      project: PROJECT
  template:
    metadata:
      namespace: NAMESPACE
      labels:
        project: PROJECT
    spec:
      containers:
         - name: PROJECT
           image: REGISTRY_HOSTNAME/PROJECT:TAG_VERSION
           ports:
             - containerPort: PORT_CONTAINER

           env:
             - name: FILES_SERVICE_PORT
               valueFrom:
                 secretKeyRef:
                   name: backend-inctagram-production-config-secret
                   key: FILES_SERVICE_PORT
             - name: FILES_SERVICE_HOST
               valueFrom:
                 secretKeyRef:
                   name: backend-inctagram-production-config-secret
                   key: FILES_SERVICE_HOST
             - name: GOOGLE_API_KEY
               valueFrom:
                 secretKeyRef:
                   name: backend-inctagram-production-config-secret
                   key: GOOGLE_API_KEY
             - name: GOOGLE_OAUTH_CLIENT_ID
               valueFrom:
                 secretKeyRef:
                   name: backend-inctagram-production-config-secret
                   key: GOOGLE_OAUTH_CLIENT_ID
             - name: GOOGLE_OAUTH_CLIENT_SECRET
               valueFrom:
                 secretKeyRef:
                   name: backend-inctagram-production-config-secret
                   key: GOOGLE_OAUTH_CLIENT_SECRET
             - name: TEST_DB_URL
               valueFrom:
                 secretKeyRef:
                   name: backend-inctagram-production-config-secret
                   key: TEST_DB_URL
             - name: DB_URL
               valueFrom:
                 secretKeyRef:
                   name: backend-inctagram-production-config-secret
                   key: DB_URL
